export const notebookKeys = {
  all: ["notebooks"] as const,
  list: () => [...notebookKeys.all, "list"] as const,
  detail: (notebookId: string) =>
    [...notebookKeys.all, "detail", notebookId] as const,
  create: () => [...notebookKeys.all, "create"] as const,
  upload: () => [...notebookKeys.all, "upload"] as const,
  uploadUrl: () => [...notebookKeys.all, "upload-url"] as const,
  removeSource: () => [...notebookKeys.all, "remove-source"] as const,
  summary: () => [...notebookKeys.all, "summary"] as const,
  mindmap: () => [...notebookKeys.all, "mindmap"] as const,
  flashcards: () => [...notebookKeys.all, "flashcards"] as const,
  voices: () => [...notebookKeys.all, "voices"] as const,
  podcast: () => [...notebookKeys.all, "podcast"] as const,
  contour: () => [...notebookKeys.all, "contour"] as const,
  transcribe: () => [...notebookKeys.all, "transcribe"] as const,
  chat: (notebookId: string) =>
    [...notebookKeys.detail(notebookId), "chat"] as const,
  contract: () => [...notebookKeys.all, "contract"] as const,
  knowledgeGraph: () => [...notebookKeys.all, "knowledge-graph"] as const,
  timeline: () => [...notebookKeys.all, "timeline"] as const,
  questions: () => [...notebookKeys.all, "questions"] as const,
  presentation: () => [...notebookKeys.all, "presentation"] as const,
  checkFlashcard: () => [...notebookKeys.all, "flashcards-check"] as const,
  search: () => [...notebookKeys.all, "search"] as const,
  compare: () => [...notebookKeys.all, "compare"] as const,
};
