/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotebooksRouteRouteImport } from './routes/notebooks/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotebooksIndexRouteImport } from './routes/notebooks/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebooksRouteRoute = NotebooksRouteRouteImport.update({
  id: '/notebooks',
  path: '/notebooks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebooksIndexRoute = NotebooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotebooksRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notebooks': typeof NotebooksRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/notebooks/': typeof NotebooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notebooks': typeof NotebooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notebooks': typeof NotebooksRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/notebooks/': typeof NotebooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/notebooks' | '/login' | '/notebooks/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/notebooks'
  id: '__root__' | '/' | '/notebooks' | '/login' | '/notebooks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotebooksRouteRoute: typeof NotebooksRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebooks': {
      id: '/notebooks'
      path: '/notebooks'
      fullPath: '/notebooks'
      preLoaderRoute: typeof NotebooksRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebooks/': {
      id: '/notebooks/'
      path: '/'
      fullPath: '/notebooks/'
      preLoaderRoute: typeof NotebooksIndexRouteImport
      parentRoute: typeof NotebooksRouteRoute
    }
  }
}

interface NotebooksRouteRouteChildren {
  NotebooksIndexRoute: typeof NotebooksIndexRoute
}

const NotebooksRouteRouteChildren: NotebooksRouteRouteChildren = {
  NotebooksIndexRoute: NotebooksIndexRoute,
}

const NotebooksRouteRouteWithChildren = NotebooksRouteRoute._addFileChildren(
  NotebooksRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotebooksRouteRoute: NotebooksRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
